import { Package, Truck } from "lucide-react";

export const categories = {
  Electronics: {
    IoT: ["Smart Home Systems", "Weather Monitoring", "Asset Tracking"],
    Embedded: ["Microcontroller Projects", "FPGA Designs", "Real-time Systems"],
    Automation: ["Home Automation", "Industrial Control", "Robotics Control"],
    "Power Electronics": ["Inverters", "Battery Management", "Solar Systems"],
  },
  Mechanical: {
    "CAD Design": ["3D Modeling", "Assembly Design", "Technical Drawing"],
    Manufacturing: ["CNC Projects", "3D Printing", "Fabrication"],
    Robotics: ["Mechanical Arms", "Mobile Robots", "Actuator Systems"],
    Thermal: ["Heat Exchangers", "Cooling Systems", "Energy Systems"],
  },
  Electrical: {
    "Power Systems": [
      "Grid Analysis",
      "Protection Systems",
      "Renewable Energy",
    ],
    "Control Systems": ["PID Controllers", "Motor Drives", "Process Control"],
    "Circuit Design": ["Analog Circuits", "Digital Circuits", "PCB Design"],
    Instrumentation: ["Measurement Systems", "Data Acquisition", "Sensors"],
  },
  Software: {
    "Web Development": ["Full Stack Apps", "E-commerce", "Portfolio Sites"],
    "Mobile Apps": ["Android Apps", "iOS Apps", "Cross Platform"],
    "AI/ML": ["Computer Vision", "NLP Projects", "Predictive Models"],
    "Data Science": ["Analytics Dashboard", "Visualization", "Big Data"],
  },
  Civil: {
    Structural: ["Bridge Design", "Building Analysis", "Foundation Design"],
    Environmental: ["Water Treatment", "Air Quality", "Waste Management"],
    Transportation: ["Traffic Systems", "Road Design", "Urban Planning"],
    Geotechnical: ["Soil Analysis", "Slope Stability", "Foundation Systems"],
  },
  Mechatronics: {
    Robotics: ["Autonomous Vehicles", "Industrial Robots", "Service Robots"],
    Automation: ["Factory Automation", "Process Control", "Quality Control"],
    "Smart Systems": ["IoT Integration", "Sensor Networks", "Edge Computing"],
    "Control Engineering": [
      "Motion Control",
      "System Integration",
      "HMI Design",
    ],
  },
};

export const mockProducts = [
  {
    id: "1",
    title: "Smart Home Automation System",
    category: "Electronics",
    subcategory: "IoT",
    price: 2499,
    originalPrice: 3499,
    image: "/placeholder.svg?height=300&width=400",
    description:
      "Complete IoT-based home automation system with mobile app control, voice commands, and energy monitoring.",
    components: [
      "ESP32",
      "Relay Modules",
      "Sensors",
      "Mobile App",
      "PCB",
      "Enclosure",
    ],
    difficulty: "Intermediate",
    rating: 4.8,
    reviews: 124,
  },
  {
    id: "2",
    title: "Autonomous Line Following Robot",
    category: "Mechatronics",
    subcategory: "Robotics",
    price: 1899,
    originalPrice: 2499,
    image: "/placeholder.svg?height=300&width=400",
    description:
      "Advanced line following robot with obstacle avoidance, PID control, and wireless monitoring.",
    components: [
      "Arduino Uno",
      "Motors",
      "Sensors",
      "Chassis",
      "Battery Pack",
      "Wheels",
    ],
    difficulty: "Beginner",
    rating: 4.6,
    reviews: 89,
  },
  {
    id: "3",
    title: "Solar Power Management System",
    category: "Electrical",
    subcategory: "Power Systems",
    price: 3299,
    originalPrice: 4199,
    image: "/placeholder.svg?height=300&width=400",
    description:
      "Complete solar power management with MPPT controller, battery monitoring, and grid tie functionality.",
    components: [
      "Solar Panel",
      "MPPT Controller",
      "Battery",
      "Inverter",
      "Monitoring System",
    ],
    difficulty: "Advanced",
    rating: 4.9,
    reviews: 67,
  },
  {
    id: "4",
    title: "AI-Powered Security Camera",
    category: "Software",
    subcategory: "AI/ML",
    price: 2799,
    originalPrice: 3599,
    image: "/placeholder.svg?height=300&width=400",
    description:
      "Smart security camera with facial recognition, motion detection, and real-time alerts.",
    components: [
      "Raspberry Pi",
      "Camera Module",
      "AI Software",
      "Mobile App",
      "Cloud Storage",
    ],
    difficulty: "Advanced",
    rating: 4.7,
    reviews: 156,
  },
  {
    id: "5",
    title: "Structural Health Monitoring",
    category: "Civil",
    subcategory: "Structural",
    price: 4299,
    originalPrice: 5499,
    image: "/placeholder.svg?height=300&width=400",
    description:
      "IoT-based structural health monitoring system for bridges and buildings with real-time analysis.",
    components: [
      "Strain Gauges",
      "Accelerometers",
      "Data Logger",
      "Analysis Software",
      "Dashboard",
    ],
    difficulty: "Advanced",
    rating: 4.8,
    reviews: 43,
  },
  {
    id: "6",
    title: "CNC Drawing Machine",
    category: "Mechanical",
    subcategory: "Manufacturing",
    price: 3799,
    originalPrice: 4799,
    image: "/placeholder.svg?height=300&width=400",
    description:
      "3-axis CNC machine for precise drawing and light engraving with G-code support.",
    components: [
      "Stepper Motors",
      "Linear Rails",
      "Control Board",
      "Software",
      "Frame",
      "Tools",
    ],
    difficulty: "Intermediate",
    rating: 4.5,
    reviews: 78,
  },
  {
    id: "7",
    title: "RFID Access Control System",
    category: "Electronics",
    subcategory: "Embedded",
    price: 1899,
    originalPrice: 2499,
    image: "/placeholder.svg?height=300&width=400",
    description:
      "Advanced RFID-based access control with database logging and mobile notifications.",
    components: [
      "Arduino",
      "RFID Module",
      "LCD Display",
      "Buzzer",
      "Database",
      "Mobile App",
    ],
    difficulty: "Beginner",
    rating: 4.6,
    reviews: 89,
  },
  {
    id: "8",
    title: "Wireless Weather Station",
    category: "Electronics",
    subcategory: "IoT",
    price: 1599,
    originalPrice: 2199,
    image: "/placeholder.svg?height=300&width=400",
    description:
      "IoT weather monitoring station with cloud data logging and real-time alerts.",
    components: [
      "NodeMCU",
      "Weather Sensors",
      "Solar Panel",
      "Battery",
      "Cloud Platform",
    ],
    difficulty: "Intermediate",
    rating: 4.7,
    reviews: 156,
  },
  {
    id: "9",
    title: "AI Chatbot Platform",
    category: "Software",
    subcategory: "AI/ML",
    price: 3299,
    originalPrice: 4199,
    image: "/placeholder.svg?height=300&width=400",
    description:
      "Complete chatbot development platform with NLP, machine learning, and deployment tools.",
    components: [
      "Python Code",
      "ML Models",
      "Web Interface",
      "API Documentation",
      "Database",
    ],
    difficulty: "Advanced",
    rating: 4.9,
    reviews: 67,
  },
  {
    id: "10",
    title: "E-Commerce Web Application",
    category: "Software",
    subcategory: "Web Development",
    price: 2799,
    originalPrice: 3599,
    image: "/placeholder.svg?height=300&width=400",
    description:
      "Full-stack e-commerce platform with payment integration, admin panel, and mobile responsiveness.",
    components: [
      "React.js",
      "Node.js",
      "MongoDB",
      "Payment Gateway",
      "Admin Panel",
    ],
    difficulty: "Intermediate",
    rating: 4.8,
    reviews: 203,
  },
  {
    id: "11",
    title: "3D Printed Robotic Arm",
    category: "Mechanical",
    subcategory: "Robotics",
    price: 4299,
    originalPrice: 5499,
    image: "/placeholder.svg?height=300&width=400",
    description:
      "6-DOF robotic arm with 3D printed parts, servo control, and programming interface.",
    components: [
      "3D Printed Parts",
      "Servo Motors",
      "Control Board",
      "Software",
      "Assembly Guide",
    ],
    difficulty: "Advanced",
    rating: 4.8,
    reviews: 43,
  },
  {
    id: "12",
    title: "Motor Speed Controller",
    category: "Electrical",
    subcategory: "Control Systems",
    price: 1899,
    originalPrice: 2499,
    image: "/placeholder.svg?height=300&width=400",
    description:
      "Variable frequency drive for AC motor speed control with PID regulation.",
    components: [
      "VFD Module",
      "Control Circuit",
      "Display",
      "Sensors",
      "Protection Circuit",
    ],
    difficulty: "Intermediate",
    rating: 4.6,
    reviews: 92,
  },
  {
    id: "13",
    title: "Smart Traffic Management",
    category: "Civil",
    subcategory: "Transportation",
    price: 3599,
    originalPrice: 4299,
    image: "/placeholder.svg?height=300&width=400",
    description:
      "AI-powered traffic management system with real-time optimization and monitoring.",
    components: [
      "Cameras",
      "AI Software",
      "Traffic Controllers",
      "Dashboard",
      "Mobile App",
    ],
    difficulty: "Advanced",
    rating: 4.7,
    reviews: 78,
  },
  {
    id: "14",
    title: "Industrial Automation PLC",
    category: "Mechatronics",
    subcategory: "Automation",
    price: 4599,
    originalPrice: 5799,
    image: "/placeholder.svg?height=300&width=400",
    description:
      "Complete PLC-based industrial automation system with HMI and SCADA integration.",
    components: [
      "PLC Module",
      "HMI Panel",
      "Sensors",
      "Actuators",
      "SCADA Software",
    ],
    difficulty: "Advanced",
    rating: 4.9,
    reviews: 56,
  },
  {
    id: "15",
    title: "Drone Flight Controller",
    category: "Electronics",
    subcategory: "Embedded",
    price: 2299,
    originalPrice: 2999,
    image: "/placeholder.svg?height=300&width=400",
    description:
      "Custom flight controller for quadcopter with GPS navigation and autonomous flight modes.",
    components: [
      "Flight Controller",
      "GPS Module",
      "IMU Sensors",
      "ESCs",
      "Propellers",
      "Frame",
    ],
    difficulty: "Advanced",
    rating: 4.8,
    reviews: 134,
  },
];

export const shippingSteps = [
  {
    icon: Package,
    label: "Order Confirmed",
    description: "Your order has been placed",
  },
  {
    icon: Package,
    label: "Processing",
    description: "Preparing your project kit",
  },
  { icon: Truck, label: "Shipped", description: "On the way to you" },
];

export const categoryProducts = {
  Electronics: [mockProducts[0], mockProducts[6], mockProducts[7]],
  Software: [
    mockProducts[8],
    mockProducts[9],
    {
      id: "s3",
      title: "Mobile App with Backend",
      category: "Software",
      subcategory: "Mobile Apps",
      price: 2299,
      originalPrice: 2999,
      image: "/placeholder.svg?height=300&width=400",
      description:
        "Cross-platform mobile application with REST API backend and real-time features.",
      components: [
        "React Native",
        "Express.js",
        "Firebase",
        "Push Notifications",
        "Analytics",
      ],
      difficulty: "Advanced",
      rating: 4.7,
      reviews: 134,
    },
  ],
  Mechanical: [mockProducts[10], mockProducts[5]],
  Electrical: [mockProducts[2], mockProducts[11]],
};

export const mockOrders = [
  {
    id: "EP123456",
    date: "2024-01-15",
    status: "Delivered",
    total: 2499,
    items: [
      {
        title: "Smart Home Automation System",
        quantity: 1,
        price: 2499,
        image: "/placeholder.svg?height=100&width=100",
      },
    ],
    trackingId: "TRK789123",
    estimatedDelivery: "2024-01-20",
  },
  {
    id: "EP123457",
    date: "2024-01-10",
    status: "Shipped",
    total: 1899,
    items: [
      {
        title: "RFID Access Control System",
        quantity: 1,
        price: 1899,
        image: "/placeholder.svg?height=100&width=100",
      },
    ],
    trackingId: "TRK789124",
    estimatedDelivery: "2024-01-18",
  },
];
